Práctica 10. Ficheros. Documentación de programas. Doxygen: funciones_cripto.h File Reference
funciones_cripto.h File Reference
Functions
void Usage (int argc, char *argv[])
La funcion Usage va a comprobar el uso de los argumentos pasados por linea de comandos, y va a generar mensajes si son necesarios con con argumentos especiales como puede ser –help.
void Encrypted_Cesar (std::string input_file, std::ofstream &out, int code)
La funcion Encrypted_Cesar encriptara mediante el metodo cesar el texto de documento pasado por linea de comandos y luego lo grabara en otro archivo.
void Desencrypt_Cesar (std::string to_desencrypt, std::ofstream &out, int pass)
La funcion Desencrypt_Cesar hace todo lo contrario a Encrypted_Cesar.
void Encrypted_XOR (std::string lines_to_encrypt, std::ofstream &out, std::string secret)
La función Encrypted_XOR deberia funcionar para recibir una string obtenida desde un fichero para luego encriptarla usando el metodo XOR y luego grabar el resultado en un archivo elegido por el usuario.
void Desencrypt_XOR (std::string lines_to_desencrypt, std::ofstream &out, std::string secret)
Function Documentation
Desencrypt_Cesar()
void Desencrypt_Cesar (std::string to_desencrypt, std::ofstream & out, int pass)
La funcion Desencrypt_Cesar hace todo lo contrario a Encrypted_Cesar.
Definition at line 55 of file funciones_cripto.cc.
{
   for (char character : to_desencrypt){
     if(isalpha(character)){
       character = character - pass;
       if (character < 'A'){
         character = character + 26;
       }
     }
     out << character;
   }
 }
Referenced by main().
Desencrypt_XOR()
void Desencrypt_XOR (std::string lines_to_desencrypt, std::ofstream & out, std::string secret)
Definition at line 85 of file funciones_cripto.cc.
{
 }
Referenced by main().
Encrypted_Cesar()
void Encrypted_Cesar (std::string input_file, std::ofstream & out, int code)
La funcion Encrypted_Cesar encriptara mediante el metodo cesar el texto de documento pasado por linea de comandos y luego lo grabara en otro archivo.
https://stackoverflow.com/questions/735204/convert-a-string-in-c-to-upper-case
Definition at line 37 of file funciones_cripto.cc.
{
   std::transform(to_encrypt.begin(),to_encrypt.end(),to_encrypt.begin(), ::toupper);
   for (char character : to_encrypt){
     if(isalpha(character)){
       character = character + password;
       if (character > 'Z'){
         character = character - 26;
       }
       if (character < 'A'){
         character = character + 26;
       }
     }
   std::string encrypted_sentence = " ";
   encrypted_sentence = encrypted_sentence + character;
   out << encrypted_sentence;
   }
 }
Referenced by main().
Encrypted_XOR()
void Encrypted_XOR (std::string lines_to_encrypt, std::ofstream & out, std::string secret)
La función Encrypted_XOR deberia funcionar para recibir una string obtenida desde un fichero para luego encriptarla usando el metodo XOR y luego grabar el resultado en un archivo elegido por el usuario.
Asimismo la función Desencrypt_XOR deberia hacer la funcionalidad contraria.
Definition at line 72 of file funciones_cripto.cc.
{
   for (char character_password : secret){
     if(isalpha(character_password)){
       character_password = character_password ^ 128;
     for (char character_string : lines_to_encrypt){
     character_string = character_string ^ character_password;
     out << character_string;
       }
     }
   }
 }
Referenced by main().
Usage()
void Usage (int argc, char * argv[])
La funcion Usage va a comprobar el uso de los argumentos pasados por linea de comandos, y va a generar mensajes si son necesarios con con argumentos especiales como puede ser –help.
Definition at line 25 of file funciones_cripto.cc.
{
   if (argc > 6) {
     std::cout << "Pruebe " << argv[0] << " --help para más información" << std::endl;
     exit(EXIT_SUCCESS);
   }
   std::string parameter =argv[1];
   if (parameter == "--help") {
     std::cout << kHelpText << std::endl;
     exit(EXIT_SUCCESS);
   }
 }
References kHelpText.
Referenced by main().